import { useState, useMemo, useCallback, useEffect } from "react";

/* ═══ API LOCAL ═══ */
var API=import.meta.env.VITE_API_URL||"http://localhost:8000";
var HD={"Content-Type":"application/json"};
async function db(t,m,b,qr){try{var u=API+"/rest/v1/"+t+(qr||"");var o={method:m||"GET",headers:Object.assign({},HD)};if(b)o.body=JSON.stringify(b);var r=await fetch(u,o);if(!r.ok)return null;var tx=await r.text();return tx?JSON.parse(tx):[]}catch(e){return null}}
async function rpc(fn,pm){try{var r=await fetch(API+"/rest/v1/rpc/"+fn,{method:"POST",headers:HD,body:JSON.stringify(pm||{})});var tx=await r.text();return tx?JSON.parse(tx):null}catch(e){return null}}

/* ═══ CONSTANTS ═══ */
var SEM=4.33;
var NV=["PRE A1 STARTER","PRE A1 STARTER +","A1 MOVERS","A1 YOUNGEST","A2 FLYERS","A0","A1","A2","B1","B1 UPPER","B2","SPEAKING INICIAL","SPEAKING INT","SPEAKING AVANZADO","TALLER"];
var DI=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado"];
var HR=["9:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00"];
var MS=["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];
var ECRM=["LEAD","CONSULTANDO","INTERESADO","INSCRIPTO","NO_POR_AHORA"];
function mKey(m){var y=new Date().getFullYear();return y+"-"+(m<9?"0":"")+(m+1)}
function cMes(){return new Date().getMonth()}
function $(n){return "$"+Math.round(n).toLocaleString("es-AR")}

/* ═══ THEMES ═══ */
var Li={bg:"#f4f5f7",sf:"#fff",sfH:"#f8f9fb",bd:"#dfe2e6",bdL:"#eef0f3",tx:"#1a1d23",txM:"#4a5060",txU:"#8892a2",ac:"#4f46e5",acB:"#eef2ff",gn:"#16a34a",gnB:"#dcfce7",gnT:"#166534",or:"#ea580c",orB:"#fff7ed",rd:"#dc2626",rdB:"#fef2f2",go:"#ca8a04",goB:"#fefce8",sBg:"#e0f2fe",sBd:"#7dd3fc",sTx:"#075985",iBg:"#fff7ed",iBd:"#fdba74",iTx:"#9a3412",un:"#eef0f3"};
var Dk={bg:"#0c0f14",sf:"#14181f",sfH:"#1c2030",bd:"#252d3a",bdL:"#1e2636",tx:"#e2e6ec",txM:"#98a2b3",txU:"#5a6477",ac:"#818cf8",acB:"#1e1b4b",gn:"#4ade80",gnB:"#052e16",gnT:"#86efac",or:"#fb923c",orB:"#431407",rd:"#f87171",rdB:"#450a0a",go:"#fbbf24",goB:"#422006",sBg:"#082f49",sBd:"#0284c7",sTx:"#7dd3fc",iBg:"#431407",iBd:"#ea580c",iTx:"#fdba74",un:"#111520"};

function gSt(g,c){if(!g)return{bg:c.sf,bd:c.bd,tx:c.tx};var n=g.nivel||"";if(n.indexOf("SPEAKING")>=0)return{bg:c.sBg,bd:c.sBd,tx:c.sTx};if(g.capacidad_max<=1)return{bg:c.iBg,bd:c.iBd,tx:c.iTx};return{bg:c.gnB,bd:c.gn,tx:c.gnT}}

/* ═══ MAIN APP ═══ */
export default function App(){
  return <Panel/>;
}

function Panel(p){
var _dk=useState(false),dk=_dk[0],sDk=_dk[1];
var c=dk?Dk:Li;var F="'Inter',system-ui,sans-serif";
var _vw=useState("dashboard"),vw=_vw[0],sVw=_vw[1];
var _ld=useState(true),ld=_ld[0],sLd=_ld[1];
var _doc=useState([]),doc=_doc[0],sDoc=_doc[1];
var _tar=useState([]),tar=_tar[0],sTar=_tar[1];
var _gr=useState([]),gr=_gr[0],sGr=_gr[1];
var _gh=useState([]),gh=_gh[0],sGh=_gh[1];
var _al=useState([]),al=_al[0],sAl=_al[1];
var _dp=useState([]),dp=_dp[0],sDp=_dp[1];
var _pg=useState([]),pg=_pg[0],sPg=_pg[1];
var _mv=useState([]),mv=_mv[0],sMv=_mv[1];
var _ct=useState([]),ct=_ct[0],sCt=_ct[1];
var _sr=useState(""),sr=_sr[0],sSr=_sr[1];
var _md=useState(null),md=_md[0],sMd=_md[1];
var _ed=useState(null),ed=_ed[0],sEd=_ed[1];
var _fD=useState("all"),fD=_fD[0],sFD=_fD[1];
var _fE=useState("activo"),fE=_fE[0],sFE=_fE[1];
var _sba=useState(true),sba=_sba[0],sSba=_sba[1];
var _et=useState(null),et=_et[0],sEt=_et[1];
var _sD=useState(0),sD=_sD[0],sSD=_sD[1];
var _eD=useState(false),eD=_eD[0],sED=_eD[1];
var _pM=useState(cMes()),pM=_pM[0],sPM=_pM[1];
var _cf=useState(null),cf=_cf[0],sCf=_cf[1];
var _gs=useState(""),gs=_gs[0],sGs=_gs[1];

/* ── Load ── */
async function load(){sLd(true);try{var[d,t,g,h,a,di,pm2,m,ct2]=await Promise.all([db("docentes","GET",null,"?order=id"),db("tarifas","GET",null,"?order=docente_id,min_alumnos"),db("grupos","GET",null,"?order=id"),db("grupo_horarios","GET",null,"?order=grupo_id"),db("alumnos","GET",null,"?order=id"),db("disponibilidad","GET",null,"?order=docente_id,dia,hora"),db("pagos","GET",null,"?mes=eq."+mKey(pM)+"&order=alumno_id"),db("movimientos","GET",null,"?order=created_at.desc&limit=50"),db("contactos","GET",null,"?order=created_at.desc")]);
if(d)sDoc(d);if(t)sTar(t);if(g)sGr(g);if(h)sGh(h);if(a)sAl(a);if(di)sDp(di);if(pm2)sPg(pm2);if(m)sMv(m);if(ct2)sCt(ct2);
if(!sD&&d){var nd=d.find(function(x){return!x.es_owner});if(nd)sSD(nd.id)}}catch(e){}sLd(false)}
useEffect(function(){load()},[]);
useEffect(function(){db("pagos","GET",null,"?mes=eq."+mKey(pM)+"&order=alumno_id").then(function(r){if(r)sPg(r)})},[pM]);

/* ── Computed ── */
function gT(did,n){var ts=tar.filter(function(t){return t.docente_id===did});var r=ts.find(function(t){return n>=t.min_alumnos&&n<=t.max_alumnos});return r?r.valor_hora:0}
var act=useMemo(function(){return al.filter(function(a){return a.estado==="activo"})},[al]);
var ina=useMemo(function(){return al.filter(function(a){return a.estado==="inactivo"})},[al]);
var facB=useMemo(function(){return act.reduce(function(s,a){return s+a.monto},0)},[act]);

var gS=useMemo(function(){return gr.map(function(g2){
  var als=act.filter(function(a){return a.grupo_id===g2.id});var dc=doc.find(function(d){return d.id===g2.docente_id});
  var slots=gh.filter(function(h){return h.grupo_id===g2.id});var br=als.reduce(function(s,a){return s+a.monto},0);
  var ph=gT(g2.docente_id,als.length);var co=als.length>0?ph*g2.horas_semanales*SEM:0;
  var dd=[],hh=[];slots.forEach(function(s2){var d2=(s2.dia||"").substring(0,3);if(dd.indexOf(d2)<0)dd.push(d2);if(hh.indexOf(s2.hora)<0)hh.push(s2.hora)});
  return Object.assign({},g2,{als:als,doc:dc,slots:slots,br:br,ph:ph,co:co,nt:br-co,ds:dd.join(" "),hs2:hh.join("-")})})},[gr,act,doc,gh,tar]);

var cT=useMemo(function(){return gS.reduce(function(s,g2){return s+g2.co},0)},[gS]);
var neto=facB-cT;
var dS=useMemo(function(){return doc.map(function(d){var gps=gS.filter(function(g2){return g2.docente_id===d.id&&g2.activo});var als=act.filter(function(a){return a.docente_id===d.id});var br=als.reduce(function(s,a){return s+a.monto},0);var co=gps.reduce(function(s,g2){return s+g2.co},0);var hs=gps.reduce(function(s,g2){return s+g2.horas_semanales},0);return Object.assign({},d,{als:als,gps:gps,br:br,co:co,nt:br-co,hs:hs})})},[doc,act,gS]);

var filt=useMemo(function(){var l=fE==="activo"?act:fE==="inactivo"?ina:al;if(fD!=="all")l=l.filter(function(a){return a.docente_id===Number(fD)});if(sr)l=l.filter(function(a){return(a.nombre+" "+(a.apellido||"")).toLowerCase().indexOf(sr.toLowerCase())>=0});return l},[al,act,ina,fD,fE,sr]);

var schM=useMemo(function(){var m={};doc.forEach(function(d){m[d.id]={}});gS.filter(function(g2){return g2.activo}).forEach(function(g2){(g2.slots||[]).forEach(function(s2){m[g2.docente_id][s2.dia+"|"+s2.hora]=g2})});return m},[doc,gS]);

var gsRes=useMemo(function(){if(!gs||gs.length<2)return[];var s2=gs.toLowerCase();var res=[];al.forEach(function(a){if((a.nombre+" "+(a.apellido||"")).toLowerCase().indexOf(s2)>=0)res.push({t:"alumno",id:a.id,l:a.nombre+" "+(a.apellido||""),s:"Alumno · "+(a.estado)})});gr.forEach(function(g2){if(g2.nombre.toLowerCase().indexOf(s2)>=0)res.push({t:"grupo",id:g2.id,l:g2.nombre,s:"Grupo"})});ct.forEach(function(c2){if(c2.nombre.toLowerCase().indexOf(s2)>=0)res.push({t:"lead",id:c2.id,l:c2.nombre,s:"Lead · "+c2.estado})});return res.slice(0,8)},[gs,al,gr,ct]);

/* ── DB Ops ── */
async function uA(id,k,v){sAl(function(p2){return p2.map(function(a){return a.id===id?Object.assign({},a,{[k]:v}):a})});await db("alumnos","PATCH",{[k]:v},"?id=eq."+id);if(k==="estado")setTimeout(load,600)}
async function svAl(d2){if(d2.id){await db("alumnos","PATCH",{nombre:d2.nombre,apellido:d2.apellido||"",whatsapp:d2.whatsapp||"",nivel:d2.nivel,docente_id:d2.docente_id,grupo_id:d2.grupo_id||null,monto:d2.monto,horas_semanales:d2.horas_semanales,horario:d2.horario||""},"?id=eq."+d2.id)}else{await db("alumnos","POST",{nombre:d2.nombre,apellido:d2.apellido||"",whatsapp:d2.whatsapp||"",nivel:d2.nivel||"A1",docente_id:d2.docente_id||1,grupo_id:d2.grupo_id||null,monto:d2.monto||80000,horas_semanales:d2.horas_semanales||2,horario:d2.horario||"",estado:"activo"})}cls();load()}
async function svGr(d2){var b={nombre:d2.nombre,nivel:d2.nivel,docente_id:d2.docente_id,horas_semanales:d2.horas_semanales,capacidad_max:d2.capacidad_max};if(d2.id){await db("grupos","PATCH",b,"?id=eq."+d2.id);await db("grupo_horarios","DELETE",null,"?grupo_id=eq."+d2.id)}else{var r=await db("grupos","POST",Object.assign(b,{activo:true}));if(r&&r[0])d2.id=r[0].id}if(d2.id&&d2.slots){for(var i=0;i<d2.slots.length;i++)await db("grupo_horarios","POST",{grupo_id:d2.id,dia:d2.slots[i].dia,hora:d2.slots[i].hora})}cls();load()}
function dlGr(id){sCf({msg:"¿Eliminar este grupo? Los alumnos quedarán sin grupo.",ok:async function(){await db("alumnos","PATCH",{grupo_id:null},"?grupo_id=eq."+id);await db("grupo_horarios","DELETE",null,"?grupo_id=eq."+id);await db("grupos","DELETE",null,"?id=eq."+id);sCf(null);cls();load()}})}
async function tPay(pid,v){sPg(function(p2){return p2.map(function(x){return x.id===pid?Object.assign({},x,{pagado:v,fecha_pago:v?new Date().toISOString():null}):x})});await db("pagos","PATCH",{pagado:v,fecha_pago:v?new Date().toISOString():null},"?id=eq."+pid)}
async function genPg(){await rpc("generar_pagos_mes",{p_mes:mKey(pM)});var r=await db("pagos","GET",null,"?mes=eq."+mKey(pM)+"&order=alumno_id");if(r)sPg(r)}
async function svTar(did,tiers){await db("tarifas","DELETE",null,"?docente_id=eq."+did);for(var i=0;i<tiers.length;i++)await db("tarifas","POST",{docente_id:did,min_alumnos:tiers[i].mn,max_alumnos:tiers[i].mx,valor_hora:tiers[i].v});sEt(null);load()}
async function togDisp(docId,dia,hora){var cur=dp.find(function(x){return x.docente_id===docId&&x.dia===dia&&x.hora===hora});if(cur){await db("disponibilidad","PATCH",{disponible:!cur.disponible},"?id=eq."+cur.id)}else{await db("disponibilidad","POST",{docente_id:docId,dia:dia,hora:hora,disponible:true})}var r=await db("disponibilidad","GET",null,"?docente_id=eq."+docId+"&order=dia,hora");if(r)sDp(function(p2){return p2.filter(function(x){return x.docente_id!==docId}).concat(r)})}
async function svCt(d2){if(d2.id){await db("contactos","PATCH",{nombre:d2.nombre,whatsapp:d2.whatsapp||"",instagram:d2.instagram||"",estado:d2.estado||"LEAD",curso_interes:d2.curso_interes||"",motivo_no:d2.motivo_no||""},"?id=eq."+d2.id)}else{await db("contactos","POST",{nombre:d2.nombre,whatsapp:d2.whatsapp||"",instagram:d2.instagram||"",canal:d2.canal||"whatsapp",estado:"LEAD",curso_interes:d2.curso_interes||""})}cls();load()}
function exportCSV(){var rows=[["Alumno","Nivel","Monto","Pagado","Fecha"]];pg.forEach(function(p2){var a=al.find(function(x){return x.id===p2.alumno_id});rows.push([(a?a.nombre+" "+(a.apellido||""):""),a?a.nivel:"",p2.monto,p2.pagado?"Si":"No",p2.fecha_pago||""])});var csv=rows.map(function(r){return r.join(",")}).join("\n");var bl=new Blob([csv],{type:"text/csv"});var url=URL.createObjectURL(bl);var a2=document.createElement("a");a2.href=url;a2.download="pagos-"+mKey(pM)+".csv";a2.click()}
function cls(){sMd(null);sEd(null)}

/* ── Styles ── */
var inp={width:"100%",padding:"8px 12px",background:c.bg,border:"1px solid "+c.bd,borderRadius:8,color:c.tx,fontSize:13,fontFamily:F,outline:"none",boxSizing:"border-box"};
var sel=Object.assign({},inp,{cursor:"pointer"});
var bP={padding:"8px 16px",background:c.ac,border:"none",borderRadius:8,color:"#fff",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:F};
var bS=Object.assign({},bP,{background:"transparent",border:"1px solid "+c.bd,color:c.txM});
var th2={textAlign:"left",padding:"8px 10px",fontSize:10,color:c.txU,fontFamily:F,fontWeight:700,textTransform:"uppercase",letterSpacing:.8,borderBottom:"2px solid "+c.bd};

/* ── Shared UI ── */
function Mo(pr){if(!pr.open)return null;return <div style={{position:"fixed",inset:0,zIndex:1e3,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.35)"}} onClick={pr.onClose}><div onClick={function(e){e.stopPropagation()}} style={{background:c.sf,borderRadius:14,padding:"24px 28px",width:pr.w?"min(680px,94vw)":"min(440px,92vw)",maxHeight:"86vh",overflowY:"auto",boxShadow:"0 20px 50px rgba(0,0,0,.2)",border:"1px solid "+c.bd,animation:"su .2s"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><h3 style={{margin:0,fontSize:16,color:c.tx,fontFamily:F,fontWeight:600}}>{pr.title}</h3><button onClick={pr.onClose} style={{background:"none",border:"none",color:c.txU,cursor:"pointer",fontSize:18}}>✕</button></div>{pr.children}</div></div>}
function FL(pr){return <div style={{marginBottom:12}}><label style={{display:"block",fontSize:11,color:c.txU,marginBottom:4,fontFamily:F,fontWeight:600,textTransform:"uppercase",letterSpacing:.8}}>{pr.label}</label>{pr.children}</div>}
function EC(pr){if(pr.type==="select"&&pr.options)return <select value={pr.value==null?"":pr.value} onChange={function(e){pr.onChange(e.target.value)}} style={Object.assign({border:"none",background:"transparent",color:c.tx,fontSize:12,fontFamily:F,cursor:"pointer",padding:"2px 4px",borderRadius:4,outline:"none"},pr.style||{})}>{pr.options.map(function(o){var vl=typeof o==="object"?o.v:o;var lb=typeof o==="object"?o.l:o;return <option key={vl} value={vl}>{lb}</option>})}</select>;return <input type={pr.type||"text"} value={pr.value==null?"":pr.value} onChange={function(e){pr.onChange(pr.type==="number"?Number(e.target.value):e.target.value)}} style={Object.assign({border:"none",background:"transparent",color:c.tx,fontSize:12,fontFamily:F,padding:"2px 6px",borderRadius:4,outline:"none",width:pr.type==="number"?55:"100%"},pr.style||{})}/>}
function St(pr){return <div style={{flex:1,minWidth:pr.mw||140,background:c.sf,border:"1px solid "+c.bd,borderRadius:12,padding:"14px 16px",borderLeft:"4px solid "+pr.cl}}><div style={{fontSize:10,color:c.txU,fontFamily:F,fontWeight:600,textTransform:"uppercase",letterSpacing:.6,marginBottom:5}}>{pr.l}</div><div style={{fontSize:20,fontWeight:700,color:pr.cl,fontFamily:F}}>{pr.v}</div>{pr.s&&<div style={{fontSize:11,color:c.txU,fontFamily:F,marginTop:2}}>{pr.s}</div>}</div>}

/* ── Forms ── */
function AFrm(pr){var _f=useState(pr.item||{nombre:"",apellido:"",whatsapp:"",grupo_id:null,docente_id:1,monto:80000,nivel:"A1",horas_semanales:2,horario:""}),f=_f[0],sF=_f[1];var s=function(k,v){sF(function(o){return Object.assign({},o,{[k]:v})})};
return <div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><FL label="Nombre"><input style={inp} value={f.nombre} onChange={function(e){s("nombre",e.target.value)}}/></FL><FL label="Apellido"><input style={inp} value={f.apellido||""} onChange={function(e){s("apellido",e.target.value)}}/></FL></div><FL label="WhatsApp"><input style={inp} value={f.whatsapp||""} onChange={function(e){s("whatsapp",e.target.value)}} placeholder="+54 11..."/></FL><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><FL label="Profesor"><select style={sel} value={f.docente_id} onChange={function(e){s("docente_id",Number(e.target.value))}}>{doc.map(function(d){return <option key={d.id} value={d.id}>{d.nombre}</option>})}</select></FL><FL label="Nivel"><select style={sel} value={f.nivel} onChange={function(e){s("nivel",e.target.value)}}>{NV.map(function(n){return <option key={n}>{n}</option>})}</select></FL></div><FL label="Grupo"><select style={sel} value={f.grupo_id||""} onChange={function(e){s("grupo_id",e.target.value?Number(e.target.value):null)}}><option value="">Individual</option>{gr.filter(function(g2){return g2.activo}).map(function(g2){return <option key={g2.id} value={g2.id}>{g2.nombre}</option>})}</select></FL><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}><FL label="Monto"><input style={inp} type="number" value={f.monto} onChange={function(e){s("monto",Number(e.target.value))}}/></FL><FL label="Hs/sem"><input style={inp} type="number" value={f.horas_semanales} onChange={function(e){s("horas_semanales",Number(e.target.value))}}/></FL><FL label="Horario"><input style={inp} value={f.horario||""} onChange={function(e){s("horario",e.target.value)}}/></FL></div><div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:10}}><button style={bS} onClick={pr.onClose}>Cancelar</button><button style={bP} onClick={function(){pr.onSave(f)}}>{f.id?"Guardar":"Inscribir"}</button></div></div>}

function GFrm(pr){var it=pr.item;var eSlots=it?gh.filter(function(h2){return h2.grupo_id===it.id}).map(function(h2){return{dia:h2.dia,hora:h2.hora}}):[];var _f=useState({nombre:it?it.nombre:"",nivel:it?it.nivel:"A1",docente_id:it?it.docente_id:2,horas_semanales:it?it.horas_semanales:2,capacidad_max:it?it.capacidad_max:5,slots:eSlots,id:it?it.id:null}),f=_f[0],sF=_f[1];var s=function(k,v){sF(function(o){return Object.assign({},o,{[k]:v})})};var sls=f.slots||[];var gAls=it?act.filter(function(a){return a.grupo_id===it.id}):[];
return <div><FL label="Nombre"><input style={inp} value={f.nombre} onChange={function(e){s("nombre",e.target.value)}}/></FL><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}><FL label="Nivel"><select style={sel} value={f.nivel} onChange={function(e){s("nivel",e.target.value)}}>{NV.map(function(n){return <option key={n}>{n}</option>})}</select></FL><FL label="Profesor"><select style={sel} value={f.docente_id} onChange={function(e){s("docente_id",Number(e.target.value))}}>{doc.map(function(d){return <option key={d.id} value={d.id}>{d.nombre}</option>})}</select></FL><FL label="Cap"><input style={inp} type="number" value={f.capacidad_max} onChange={function(e){s("capacidad_max",Number(e.target.value))}}/></FL></div>
<FL label="Horarios">{sls.map(function(sl,i){return <div key={i} style={{display:"flex",gap:6,marginBottom:6}}><select style={Object.assign({},sel,{flex:1})} value={sl.dia} onChange={function(e){var n=sls.slice();n[i]={dia:e.target.value,hora:n[i].hora};s("slots",n)}}>{DI.map(function(d){return <option key={d}>{d}</option>})}</select><select style={Object.assign({},sel,{flex:1})} value={sl.hora} onChange={function(e){var n=sls.slice();n[i]={dia:n[i].dia,hora:e.target.value};s("slots",n)}}>{HR.map(function(h2){return <option key={h2}>{h2}</option>})}</select><button onClick={function(){s("slots",sls.filter(function(_,j){return j!==i}))}} style={{background:"none",border:"none",color:c.rd,cursor:"pointer",fontSize:15}}>✕</button></div>})}<button onClick={function(){s("slots",sls.concat([{dia:"Lunes",hora:"9:00"}]))}} style={Object.assign({},bS,{padding:"4px 12px",fontSize:11})}>+ Slot</button></FL>
<FL label="Hs/sem"><input style={inp} type="number" value={f.horas_semanales} onChange={function(e){s("horas_semanales",Number(e.target.value))}}/></FL>
{it&&<div style={{marginTop:6,padding:10,background:c.bg,borderRadius:10}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:11,fontWeight:700,color:c.txU,fontFamily:F}}>ALUMNOS ({gAls.length}/{f.capacidad_max})</span><button style={Object.assign({},bP,{padding:"3px 10px",fontSize:11})} onClick={function(){sMd("addgr-"+it.id)}}>+ Agregar</button></div>{gAls.map(function(a){return <div key={a.id} style={{display:"flex",justifyContent:"space-between",padding:"3px 0",borderBottom:"1px solid "+c.bdL,fontSize:12,fontFamily:F}}><span>{a.nombre} {a.apellido||""}</span><div style={{display:"flex",gap:6,alignItems:"center"}}><span style={{color:c.txU}}>{$(a.monto)}</span><button onClick={function(){uA(a.id,"grupo_id",null)}} style={{background:"none",border:"none",color:c.rd,cursor:"pointer",fontSize:12}}>✕</button></div></div>})}</div>}
<div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:10}}>{it&&<button style={Object.assign({},bP,{background:c.rd})} onClick={function(){pr.onDelete(it.id)}}>Eliminar</button>}<div style={{flex:1}}/><button style={bS} onClick={pr.onClose}>Cancelar</button><button style={bP} onClick={function(){pr.onSave(f)}}>{it?"Guardar":"Crear"}</button></div></div>}

function TFrm(pr){var curr=tar.filter(function(t){return t.docente_id===pr.did}).map(function(t){return{mn:t.min_alumnos,mx:t.max_alumnos,v:t.valor_hora}});var _f=useState(curr.length?curr:[{mn:1,mx:1,v:5000}]),ti=_f[0],sTi=_f[1];return <div>{ti.map(function(r,i){return <div key={i} style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:8}}><FL label="Desde"><input style={inp} type="number" value={r.mn} onChange={function(e){var n=ti.slice();n[i]=Object.assign({},n[i],{mn:Number(e.target.value)});sTi(n)}}/></FL><FL label="Hasta"><input style={inp} type="number" value={r.mx} onChange={function(e){var n=ti.slice();n[i]=Object.assign({},n[i],{mx:Number(e.target.value)});sTi(n)}}/></FL><FL label="$/hr"><input style={inp} type="number" value={r.v} onChange={function(e){var n=ti.slice();n[i]=Object.assign({},n[i],{v:Number(e.target.value)});sTi(n)}}/></FL></div>})}<button style={Object.assign({},bS,{marginBottom:12,fontSize:11})} onClick={function(){sTi(ti.concat([{mn:1,mx:1,v:5000}]))}}>+ Rango</button><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><button style={bS} onClick={function(){sEt(null)}}>Cancelar</button><button style={Object.assign({},bP,{background:c.go})} onClick={function(){svTar(pr.did,ti)}}>Guardar</button></div></div>}

function CFrm(pr){var _f=useState(pr.item||{nombre:"",whatsapp:"",instagram:"",canal:"whatsapp",estado:"LEAD",curso_interes:"",motivo_no:""}),f=_f[0],sF=_f[1];var s=function(k,v){sF(function(o){return Object.assign({},o,{[k]:v})})};return <div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><FL label="Nombre"><input style={inp} value={f.nombre} onChange={function(e){s("nombre",e.target.value)}}/></FL><FL label="Canal"><select style={sel} value={f.canal||"whatsapp"} onChange={function(e){s("canal",e.target.value)}}>{["whatsapp","instagram","landing","manual"].map(function(x){return <option key={x}>{x}</option>})}</select></FL></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><FL label="WhatsApp"><input style={inp} value={f.whatsapp||""} onChange={function(e){s("whatsapp",e.target.value)}}/></FL><FL label="Instagram"><input style={inp} value={f.instagram||""} onChange={function(e){s("instagram",e.target.value)}}/></FL></div><FL label="Estado"><select style={sel} value={f.estado} onChange={function(e){s("estado",e.target.value)}}>{ECRM.map(function(e){return <option key={e}>{e}</option>})}</select></FL><FL label="Interés"><input style={inp} value={f.curso_interes||""} onChange={function(e){s("curso_interes",e.target.value)}}/></FL><div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:10}}><button style={bS} onClick={pr.onClose}>Cancelar</button><button style={bP} onClick={function(){pr.onSave(f)}}>{f.id?"Guardar":"Crear lead"}</button></div></div>}

var nav=[{id:"dashboard",l:"Dashboard",i:"📊"},{id:"alumnos",l:"Alumnos",i:"👥"},{id:"profesores",l:"Profesores",i:"🎓"},{id:"grupos",l:"Grupos",i:"📚"},{id:"horarios",l:"Horarios",i:"🗓"},{id:"pagos",l:"Pagos",i:"💰"},{id:"crm",l:"CRM",i:"📱"}];
var addGrId=md&&typeof md==="string"&&md.startsWith("addgr-")?Number(md.replace("addgr-","")):null;

/* ═══ VIEWS ═══ */
function VDash(){return <div style={{animation:"fi .3s"}}><div style={{display:"flex",flexWrap:"wrap",gap:12,marginBottom:24}}><St l="Facturación bruta" v={$(facB)} s="Ingreso total" cl={c.ac} mw={180}/><St l="Ganancia neta" v={$(neto)} s={"Costo: "+$(cT)} cl={c.gn} mw={180}/><St l="Alumnos activos" v={act.length} s={ina.length+" inactivos"} cl={c.go} mw={140}/></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12,marginBottom:24}}>{dS.map(function(d){return <div key={d.id} style={{background:c.sf,border:"1px solid "+c.bd,borderRadius:12,padding:16}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><div style={{fontSize:15,fontWeight:600,color:c.tx,fontFamily:F}}>{d.nombre}{d.es_owner?" (Tú)":""}</div><span style={{fontSize:11,color:c.txU}}>{d.als.length}al · {d.hs}hs</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6}}>{[{l:"Bruto",v:$(d.br),cl:c.tx},{l:"Pagás",v:$(d.co),cl:c.or},{l:"Neto",v:$(d.nt),cl:c.gn}].map(function(x){return <div key={x.l} style={{background:c.bg,borderRadius:8,padding:"6px 4px",textAlign:"center"}}><div style={{fontSize:9,color:c.txU,fontFamily:F}}>{x.l}</div><div style={{fontSize:13,fontWeight:700,color:x.cl,fontFamily:F}}>{x.v}</div></div>})}</div></div>})}</div>
{mv.length>0&&<div><div style={{fontSize:14,fontWeight:600,color:c.tx,fontFamily:F,marginBottom:8}}>Últimos movimientos</div><div style={{background:c.sf,border:"1px solid "+c.bd,borderRadius:10,padding:10}}>{mv.slice(0,10).map(function(m2,i){return <div key={i} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",borderBottom:"1px solid "+c.bdL,fontSize:12,fontFamily:F}}><span><span style={{color:m2.tipo==="baja"?c.rd:c.gn,fontWeight:600}}>{m2.tipo==="alta"?"↑ Alta":m2.tipo==="baja"?"↓ Baja":"↑ React."}</span> {m2.nombre_alumno}</span><span style={{color:c.txU}}>{m2.mes}</span></div>})}</div></div>}</div>}

function VAlum(){return <div style={{animation:"fi .3s"}}><div style={{display:"flex",flexWrap:"wrap",gap:8,marginBottom:14}}><input style={Object.assign({},inp,{flex:"1 1 180px"})} placeholder="🔍 Buscar alumno..." value={sr} onChange={function(e){sSr(e.target.value)}}/><select style={Object.assign({},sel,{width:"auto",minWidth:110})} value={fD} onChange={function(e){sFD(e.target.value)}}><option value="all">Todos</option>{doc.map(function(d){return <option key={d.id} value={d.id}>{d.nombre}</option>})}</select><select style={Object.assign({},sel,{width:"auto",minWidth:90})} value={fE} onChange={function(e){sFE(e.target.value)}}><option value="activo">Activos</option><option value="inactivo">Inactivos</option><option value="todos">Todos</option></select><button style={bP} onClick={function(){sEd(null);sMd("al")}}>+ Inscribir</button></div>
<div style={{fontSize:12,color:c.txU,marginBottom:6,fontFamily:F}}>{filt.length} alumnos · {$(filt.reduce(function(s,a){return s+a.monto},0))}</div>
<div style={{overflowX:"auto",background:c.sf,borderRadius:10,border:"1px solid "+c.bd}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1000}}><thead><tr>{["Nombre","Apellido","WhatsApp","Nivel","Grupo","Horario","Hs","Profesor","Monto","Estado"].map(function(h2){return <th key={h2} style={th2}>{h2}</th>})}</tr></thead><tbody>{filt.map(function(a){var g2=gS.find(function(x){return x.id===a.grupo_id});return <tr key={a.id} style={{borderBottom:"1px solid "+c.bdL}} onMouseEnter={function(e){e.currentTarget.style.background=c.sfH}} onMouseLeave={function(e){e.currentTarget.style.background=""}}>
<td style={{padding:"5px 8px"}}><EC value={a.nombre} onChange={function(v){uA(a.id,"nombre",v)}}/></td>
<td style={{padding:"5px 8px"}}><EC value={a.apellido} onChange={function(v){uA(a.id,"apellido",v)}}/></td>
<td style={{padding:"5px 8px"}}><EC value={a.whatsapp} onChange={function(v){uA(a.id,"whatsapp",v)}} style={{fontSize:11,color:c.txU}}/></td>
<td style={{padding:"5px 8px"}}><EC type="select" value={a.nivel} onChange={function(v){uA(a.id,"nivel",v)}} options={NV}/></td>
<td style={{padding:"5px 8px",fontSize:11,color:c.txM,fontFamily:F}}>{g2?g2.nombre:"—"}</td>
<td style={{padding:"5px 8px"}}><EC value={a.horario} onChange={function(v){uA(a.id,"horario",v)}} style={{fontSize:11}}/></td>
<td style={{padding:"5px 8px"}}><EC type="number" value={a.horas_semanales} onChange={function(v){uA(a.id,"horas_semanales",v)}} style={{width:35}}/></td>
<td style={{padding:"5px 8px"}}><EC type="select" value={a.docente_id} onChange={function(v){uA(a.id,"docente_id",Number(v))}} options={doc.map(function(d){return{v:d.id,l:d.nombre}})}/></td>
<td style={{padding:"5px 8px"}}><EC type="number" value={a.monto} onChange={function(v){uA(a.id,"monto",v)}} style={{fontWeight:600}}/></td>
<td style={{padding:"5px 8px"}}><EC type="select" value={a.estado} onChange={function(v){uA(a.id,"estado",v)}} options={["activo","inactivo"]}/></td></tr>})}</tbody></table></div></div>}

function VProf(){return <div style={{animation:"fi .3s"}}>{dS.map(function(d){var ts=tar.filter(function(t){return t.docente_id===d.id});return <div key={d.id} style={{background:c.sf,border:"1px solid "+c.bd,borderRadius:12,padding:20,marginBottom:16}}>
<div style={{display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:8,marginBottom:14}}><div><span style={{fontSize:17,fontWeight:700,color:c.tx,fontFamily:F}}>{d.nombre}</span>{d.es_owner&&<span style={{fontSize:12,color:c.txU,marginLeft:8}}>(Tú)</span>}<div style={{fontSize:12,color:c.txU,fontFamily:F}}>{d.als.length}al · {d.gps.length}grp · {d.hs}hs/sem</div></div><div style={{display:"flex",gap:6}}>{[{l:"Bruto",v:$(d.br),cl:c.tx,bg:c.bg},{l:"Pagás",v:$(d.co),cl:c.or,bg:c.orB},{l:"Neto",v:$(d.nt),cl:c.gn,bg:c.gnB}].map(function(x){return <div key={x.l} style={{background:x.bg,borderRadius:8,padding:"5px 12px",textAlign:"center"}}><div style={{fontSize:9,color:c.txU,fontFamily:F}}>{x.l}</div><div style={{fontSize:14,fontWeight:700,color:x.cl,fontFamily:F}}>{x.v}</div></div>})}</div></div>
{ts.length>0&&<div style={{background:c.goB,borderRadius:10,padding:12,marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:11,color:c.go,fontWeight:700,fontFamily:F}}>TARIFAS</span><button onClick={function(){sEt(d.id)}} style={Object.assign({},bS,{padding:"3px 10px",fontSize:10,color:c.go})}>Editar</button></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{ts.map(function(t,i){return <div key={i} style={{background:c.sf,borderRadius:8,padding:"4px 12px",textAlign:"center"}}><div style={{fontSize:10,color:c.txU,fontFamily:F}}>{t.min_alumnos===t.max_alumnos?t.min_alumnos:t.min_alumnos+"-"+t.max_alumnos}al</div><div style={{fontSize:15,fontWeight:700,color:c.go,fontFamily:F}}>{$(t.valor_hora)}<span style={{fontSize:10,color:c.txU}}>/hr</span></div></div>})}</div></div>}
{!d.es_owner&&d.gps.length>0&&<div style={{background:c.bg,borderRadius:10,padding:10}}><div style={{fontSize:11,color:c.txU,fontFamily:F,fontWeight:600,marginBottom:6}}>DETALLE POR GRUPO</div>{d.gps.map(function(g2){return <div key={g2.id} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid "+c.bdL,fontSize:12,fontFamily:F}}><span style={{color:c.tx,fontWeight:500}}>{g2.nombre} <span style={{color:c.txU}}>· {g2.als.length}al · {g2.ds} · {g2.horas_semanales}hs</span></span><span><span style={{color:c.txU}}>{$(g2.ph)}/hr × {g2.horas_semanales} × 4.3 = </span><span style={{color:c.or,fontWeight:700}}>{$(g2.co)}</span></span></div>})}</div>}
</div>})}</div>}

function VGrup(){return <div style={{animation:"fi .3s"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:14}}><span style={{fontSize:12,color:c.txU,fontFamily:F}}>{gr.filter(function(g2){return g2.activo}).length} grupos</span><button style={bP} onClick={function(){sEd(null);sMd("gr")}}>+ Nuevo grupo</button></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:12}}>{gS.filter(function(g2){return g2.activo}).map(function(g2){var gs2=gSt(g2,c);var pct=g2.capacidad_max>0?(g2.als.length/g2.capacidad_max)*100:0;var bC=pct>=100?c.rd:pct>=80?c.go:c.gn;return <div key={g2.id} style={{background:c.sf,border:"1px solid "+c.bd,borderRadius:12,padding:14,borderTop:"3px solid "+gs2.bd}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><div><div style={{fontSize:14,fontWeight:600,color:c.tx,fontFamily:F}}>{g2.nombre}</div><div style={{fontSize:11,color:c.txU,fontFamily:F}}>{(g2.doc||{}).nombre} · {g2.ds} {g2.hs2} · {g2.horas_semanales}hs</div></div><button onClick={function(){sEd(g2);sMd("gr")}} style={{background:c.bg,border:"1px solid "+c.bd,borderRadius:6,padding:"3px 6px",color:c.txU,cursor:"pointer",fontSize:12}}>✎</button></div>
<div style={{display:"flex",alignItems:"center",gap:6,marginBottom:8}}><div style={{flex:1,height:5,background:c.bg,borderRadius:3,overflow:"hidden"}}><div style={{width:Math.min(pct,100)+"%",height:"100%",background:bC,borderRadius:3,transition:"width .5s"}}/></div><span style={{fontSize:11,color:bC,fontWeight:700,fontFamily:F}}>{g2.als.length}/{g2.capacidad_max}</span></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:4}}>{[{l:"Bruto",v:$(g2.br),cl:c.tx},{l:"$/hr",v:$(g2.ph),cl:c.go},{l:"Costo",v:$(g2.co),cl:c.or},{l:"Neto",v:$(g2.nt),cl:c.gn}].map(function(x){return <div key={x.l} style={{background:c.bg,borderRadius:6,padding:"4px 3px",textAlign:"center"}}><div style={{fontSize:9,color:c.txU,fontFamily:F}}>{x.l}</div><div style={{fontSize:11,fontWeight:600,color:x.cl,fontFamily:F}}>{x.v}</div></div>})}</div>
{g2.als.length>0&&<div style={{marginTop:6}}>{g2.als.map(function(a){return <div key={a.id} style={{display:"flex",justifyContent:"space-between",padding:"2px 0",borderTop:"1px solid "+c.bdL,fontSize:11,fontFamily:F}}><span style={{color:c.txM}}>{a.nombre} {a.apellido||""}</span><span style={{color:c.tx,fontWeight:600}}>{$(a.monto)}</span></div>})}</div>}
</div>})}</div></div>}

function VHor(){var ddMap={};dp.filter(function(x){return x.docente_id===sD}).forEach(function(x){if(x.disponible)ddMap[x.dia+"|"+x.hora]=true});var occ=schM[sD]||{};var oH=0,aH=0;DI.forEach(function(dia){HR.forEach(function(h2){var k=dia+"|"+h2;if(occ[k])oH++;else if(ddMap[k])aH++})});
return <div style={{animation:"fi .3s"}}><div style={{display:"flex",gap:6,marginBottom:14,flexWrap:"wrap",alignItems:"center"}}>{doc.filter(function(d){return!d.es_owner}).map(function(d){return <button key={d.id} onClick={function(){sSD(d.id)}} style={{padding:"6px 14px",borderRadius:8,border:"1px solid "+(sD===d.id?c.ac:c.bd),background:sD===d.id?c.acB:c.sf,color:sD===d.id?c.ac:c.txM,fontSize:12,fontWeight:600,fontFamily:F,cursor:"pointer"}}>{d.nombre}</button>})}
<button style={Object.assign({},bP,{padding:"6px 14px",fontSize:12})} onClick={function(){sEd(null);sMd("al")}}>+ Alumno</button><button style={Object.assign({},bS,{padding:"6px 14px",fontSize:12})} onClick={function(){sEd(null);sMd("gr")}}>+ Grupo</button>
<div style={{marginLeft:"auto",display:"flex",gap:8,fontSize:12,fontFamily:F}}><span style={{color:c.txU}}>Ocup: <b style={{color:c.ac}}>{oH}</b></span><span style={{color:c.txU}}>Libres: <b style={{color:c.gn}}>{aH}</b></span></div>
<button onClick={function(){sED(!eD)}} style={Object.assign({},bS,{padding:"5px 12px",fontSize:11,background:eD?c.acB:"transparent",color:eD?c.ac:c.txM})}>{eD?"✓ Listo":"✎ Disp."}</button></div>
<div style={{overflowX:"auto",background:c.sf,borderRadius:10,border:"1px solid "+c.bd}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:650}}><thead><tr><th style={Object.assign({},th2,{width:50})}>Hora</th>{DI.map(function(d){return <th key={d} style={Object.assign({},th2,{textAlign:"center"})}>{d.substring(0,3)}</th>})}</tr></thead><tbody>{HR.map(function(h2){return <tr key={h2}><td style={{padding:"2px 6px",fontSize:11,color:c.txU,fontFamily:F,fontWeight:600,borderRight:"1px solid "+c.bdL}}>{h2}</td>{DI.map(function(dia){var k=dia+"|"+h2;var g2=occ[k];var isA=ddMap[k];var isO=!!g2;var bg=c.un,bd=c.un,ct2=null,cur="default";if(isO){var gs2=gSt(g2,c);bg=gs2.bg;bd=gs2.bd;cur="pointer";ct2=<div style={{textAlign:"center"}}><div style={{fontSize:9,fontWeight:700,color:gs2.tx,fontFamily:F}}>{g2.nombre}</div><div style={{fontSize:8,color:c.txU}}>{g2.als.length}/{g2.capacidad_max}</div></div>}else if(isA){bg=c.sf;bd=c.bd}if(eD&&!isO)cur="pointer";
return <td key={dia} style={{padding:1.5}}><div onClick={function(){if(eD&&!isO)togDisp(sD,dia,h2);else if(isO){sEd(g2);sMd("gr")}}} style={{background:bg,border:"1.5px solid "+bd,borderRadius:5,padding:"5px 2px",minHeight:32,display:"flex",alignItems:"center",justifyContent:"center",cursor:cur,transition:"all .15s"}}>{ct2}{eD&&!isO&&<div style={{width:7,height:7,borderRadius:"50%",background:isA?c.gn:"#ccc"}}/>}</div></td>})}</tr>})}</tbody></table></div>
<div style={{marginTop:16}}><div style={{fontSize:13,fontWeight:600,color:c.tx,fontFamily:F,marginBottom:8}}>Grupos de {(doc.find(function(d){return d.id===sD})||{}).nombre}</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{gS.filter(function(g2){return g2.docente_id===sD&&g2.activo}).map(function(g2){var gs2=gSt(g2,c);return <div key={g2.id} onClick={function(){sEd(g2);sMd("gr")}} style={{background:gs2.bg,border:"1.5px solid "+gs2.bd,borderRadius:8,padding:"6px 12px",cursor:"pointer"}}><div style={{fontSize:12,fontWeight:600,color:gs2.tx,fontFamily:F}}>{g2.nombre}</div><div style={{fontSize:10,color:c.txU,fontFamily:F}}>{g2.ds} {g2.hs2} · {g2.als.length}/{g2.capacidad_max}al</div></div>})}</div></div></div>}

function VPag(){var mk2=mKey(pM);var paid=pg.filter(function(x){return x.pagado});var unpaid=pg.filter(function(x){return!x.pagado});var morosos=unpaid.filter(function(x){var a=al.find(function(a2){return a2.id===x.alumno_id});return a&&a.estado==="activo"});
return <div style={{animation:"fi .3s"}}><div style={{display:"flex",gap:6,marginBottom:14,alignItems:"center",flexWrap:"wrap"}}><button onClick={function(){sPM(Math.max(0,pM-1))}} style={bS}>←</button><span style={{fontSize:15,fontWeight:700,color:c.tx,fontFamily:F,minWidth:90,textAlign:"center"}}>{MS[pM]} {new Date().getFullYear()}</span><button onClick={function(){sPM(Math.min(11,pM+1))}} style={bS}>→</button><div style={{marginLeft:"auto",display:"flex",gap:6}}><button style={Object.assign({},bP,{background:c.gn,fontSize:12})} onClick={genPg}>Generar pagos</button><button style={Object.assign({},bS,{fontSize:12})} onClick={exportCSV}>📥 CSV</button></div></div>
<div style={{display:"flex",gap:4,marginBottom:16,overflowX:"auto"}}>{MS.map(function(m2,i){return <button key={i} onClick={function(){sPM(i)}} style={{padding:"6px 10px",borderRadius:6,border:"1px solid "+(i===pM?c.ac:i===cMes()?c.gn:c.bd),background:i===pM?c.acB:c.sf,color:i===pM?c.ac:c.txM,fontSize:11,fontWeight:i===pM?700:400,fontFamily:F,cursor:"pointer",minWidth:40}}>{m2}</button>})}</div>
<div style={{display:"flex",flexWrap:"wrap",gap:10,marginBottom:16}}><St l="Esperado" v={$(pg.reduce(function(s,x){return s+x.monto},0))} cl={c.ac} mw={130}/><St l="Cobrado" v={$(paid.reduce(function(s,x){return s+x.monto},0))} cl={c.gn} mw={130}/><St l="Pendiente" v={$(unpaid.reduce(function(s,x){return s+x.monto},0))} cl={c.rd} mw={130}/><St l="Pagaron" v={paid.length+"/"+pg.length} cl={c.go} mw={100}/></div>
{morosos.length>0&&<div style={{background:c.rdB,border:"1px solid "+c.rd+"40",borderRadius:10,padding:12,marginBottom:14}}><div style={{fontSize:12,fontWeight:700,color:c.rd,fontFamily:F,marginBottom:6}}>⚠ {morosos.length} alumno{morosos.length>1?"s":""} sin pagar</div>{morosos.slice(0,5).map(function(x){var a=al.find(function(a2){return a2.id===x.alumno_id});return a?<div key={x.id} style={{fontSize:12,color:c.rd,fontFamily:F,padding:"2px 0"}}>{a.nombre} {a.apellido||""} — {$(x.monto)}</div>:null})}{morosos.length>5&&<div style={{fontSize:11,color:c.txU}}>y {morosos.length-5} más...</div>}</div>}
<div style={{background:c.sf,borderRadius:10,border:"1px solid "+c.bd,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:600}}><thead><tr>{["Alumno","Nivel","Profesor","Monto","Estado","Acción"].map(function(h2){return <th key={h2} style={th2}>{h2}</th>})}</tr></thead><tbody>{pg.map(function(p2){var a=al.find(function(x){return x.id===p2.alumno_id});if(!a)return null;var d=doc.find(function(x){return x.id===a.docente_id});return <tr key={p2.id} style={{borderBottom:"1px solid "+c.bdL,background:p2.pagado?(c.gnB+"30"):""}} onMouseEnter={function(e){e.currentTarget.style.background=c.sfH}} onMouseLeave={function(e){e.currentTarget.style.background=p2.pagado?(c.gnB+"30"):""}}>
<td style={{padding:"7px 8px",fontSize:13,color:c.tx,fontFamily:F,fontWeight:500}}>{a.nombre} {a.apellido||""}</td>
<td style={{padding:"7px 8px",fontSize:12,color:c.txM,fontFamily:F}}>{a.nivel}</td>
<td style={{padding:"7px 8px",fontSize:12,color:c.txM,fontFamily:F}}>{d?d.nombre:""}</td>
<td style={{padding:"7px 8px",fontSize:13,fontWeight:600,color:c.tx,fontFamily:F}}>{$(p2.monto)}</td>
<td style={{padding:"7px 8px"}}><span style={{padding:"2px 7px",borderRadius:5,fontSize:10,fontWeight:600,background:p2.pagado?c.gnB:c.rdB,color:p2.pagado?c.gn:c.rd}}>{p2.pagado?"Pagado":"Pendiente"}</span></td>
<td style={{padding:"7px 8px"}}><button onClick={function(){tPay(p2.id,!p2.pagado)}} style={Object.assign({},p2.pagado?bS:Object.assign({},bP,{background:c.gn}),{padding:"4px 10px",fontSize:11})}>{p2.pagado?"Desmarcar":"Cobrado"}</button></td></tr>})}</tbody></table></div></div>}

function VCRM(){var funnel={};ECRM.forEach(function(e){funnel[e]=ct.filter(function(c2){return c2.estado===e}).length});
return <div style={{animation:"fi .3s"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:14}}><span style={{fontSize:12,color:c.txU,fontFamily:F}}>{ct.length} contactos</span><button style={bP} onClick={function(){sEd(null);sMd("ct")}}>+ Nuevo lead</button></div>
<div style={{display:"flex",gap:8,marginBottom:16,flexWrap:"wrap"}}>{ECRM.map(function(e){var n=funnel[e]||0;var cls2=e==="INSCRIPTO"?c.gn:e==="NO_POR_AHORA"?c.rd:e==="INTERESADO"?c.go:c.ac;return <div key={e} style={{flex:1,minWidth:120,background:c.sf,border:"1px solid "+c.bd,borderRadius:10,padding:"10px 14px",borderTop:"3px solid "+cls2,textAlign:"center"}}><div style={{fontSize:20,fontWeight:700,color:cls2,fontFamily:F}}>{n}</div><div style={{fontSize:10,color:c.txU,fontFamily:F}}>{e.replace("_"," ")}</div></div>})}</div>
<div style={{background:c.sf,borderRadius:10,border:"1px solid "+c.bd,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Nombre","WhatsApp","Instagram","Canal","Estado","Interés","Acciones"].map(function(h2){return <th key={h2} style={th2}>{h2}</th>})}</tr></thead><tbody>{ct.map(function(c2){return <tr key={c2.id} style={{borderBottom:"1px solid "+c.bdL}} onMouseEnter={function(e){e.currentTarget.style.background=c.sfH}} onMouseLeave={function(e){e.currentTarget.style.background=""}}>
<td style={{padding:"6px 8px",fontSize:13,color:c.tx,fontFamily:F,fontWeight:500}}>{c2.nombre}</td>
<td style={{padding:"6px 8px",fontSize:12,color:c.txU,fontFamily:F}}>{c2.whatsapp||"—"}</td>
<td style={{padding:"6px 8px",fontSize:12,color:c.txU,fontFamily:F}}>{c2.instagram||"—"}</td>
<td style={{padding:"6px 8px",fontSize:11,color:c.txM,fontFamily:F}}>{c2.canal}</td>
<td style={{padding:"6px 8px"}}><span style={{padding:"2px 7px",borderRadius:5,fontSize:10,fontWeight:600,background:c2.estado==="INSCRIPTO"?c.gnB:c2.estado==="NO_POR_AHORA"?c.rdB:c.acB,color:c2.estado==="INSCRIPTO"?c.gn:c2.estado==="NO_POR_AHORA"?c.rd:c.ac}}>{c2.estado}</span></td>
<td style={{padding:"6px 8px",fontSize:12,color:c.txM,fontFamily:F}}>{c2.curso_interes||""}</td>
<td style={{padding:"6px 8px"}}><button onClick={function(){sEd(c2);sMd("ct")}} style={Object.assign({},bS,{padding:"3px 10px",fontSize:11})}>Editar</button></td></tr>})}</tbody></table></div></div>}

/* ═══ RENDER ═══ */
if(ld)return <div style={{display:"flex",alignItems:"center",justifyContent:"center",minHeight:"100vh",background:c.bg,fontFamily:F}}><div style={{textAlign:"center"}}><div style={{fontSize:36,marginBottom:10}}>⏳</div><div style={{color:c.txM}}>Cargando...</div></div></div>;

return <div><style>{"@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');*{box-sizing:border-box;margin:0;padding:0}::-webkit-scrollbar{width:4px;height:4px}::-webkit-scrollbar-thumb{background:"+c.bd+";border-radius:3px}input:focus,select:focus{border-color:"+c.ac+"!important}@keyframes fi{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}@keyframes su{from{opacity:0;transform:scale(.97) translateY(8px)}to{opacity:1;transform:scale(1) translateY(0)}}"}</style>
<div style={{display:"flex",minHeight:"100vh",background:c.bg,color:c.tx,fontFamily:F,transition:"background .3s"}}>
{/* Sidebar */}
{sba&&<aside style={{width:180,background:c.sf,borderRight:"1px solid "+c.bd,padding:"16px 0",display:"flex",flexDirection:"column",position:"fixed",top:0,left:0,height:"100vh",zIndex:100,overflow:"hidden"}}>
<div style={{padding:"0 12px",marginBottom:20,display:"flex",alignItems:"center",gap:8,cursor:"pointer"}} onClick={function(){sSba(false)}}><div style={{width:26,height:26,borderRadius:8,background:c.ac,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:800,color:"#fff"}}>A</div><div style={{fontSize:13,fontWeight:700,color:c.tx}}>AburridoNT</div></div>
<nav style={{flex:1}}>{nav.map(function(n){return <button key={n.id} onClick={function(){sVw(n.id)}} style={{width:"100%",display:"flex",alignItems:"center",gap:8,padding:"8px 14px",background:vw===n.id?c.acB:"transparent",border:"none",borderLeft:vw===n.id?"3px solid "+c.ac:"3px solid transparent",color:vw===n.id?c.ac:c.txU,cursor:"pointer",fontSize:12,fontWeight:500,fontFamily:F}}><span style={{fontSize:14}}>{n.i}</span>{n.l}</button>})}</nav>
<div style={{padding:"10px 12px",borderTop:"1px solid "+c.bd}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:9,color:c.txU}}>Meta: USD 5.000</span><button onClick={function(){sDk(!dk)}} style={{background:c.bg,border:"1px solid "+c.bd,borderRadius:12,padding:"2px 6px",cursor:"pointer",fontSize:10,color:c.txM}}>{dk?"☀️":"🌙"}</button></div><div style={{height:3,background:c.bg,borderRadius:2,overflow:"hidden"}}><div style={{width:Math.min((neto/6250000)*100,100)+"%",height:"100%",background:c.ac,borderRadius:2}}/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:4}}><span style={{fontSize:9,color:c.ac,fontWeight:600}}>{((neto/6250000)*100).toFixed(0)}%</span></div></div>
</aside>}

<main style={{flex:1,padding:"18px 22px",marginLeft:sba?180:0,minWidth:0,maxWidth:1300,transition:"margin .25s"}}>
{/* Header */}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18,gap:10,flexWrap:"wrap"}}>
{!sba&&<button onClick={function(){sSba(true)}} style={{background:c.sf,border:"1px solid "+c.bd,borderRadius:8,padding:"6px 10px",cursor:"pointer",fontSize:14}}>☰</button>}
<h1 style={{fontSize:18,fontWeight:700,color:c.tx,fontFamily:F}}>{(nav.find(function(n){return n.id===vw})||{}).l}</h1>
<div style={{position:"relative",flex:"0 1 260px"}}><input value={gs} onChange={function(e){sGs(e.target.value)}} placeholder="🔍 Buscar..." style={Object.assign({},inp,{fontSize:12})}/>{gsRes.length>0&&<div style={{position:"absolute",top:"100%",left:0,right:0,background:c.sf,border:"1px solid "+c.bd,borderRadius:8,zIndex:50,boxShadow:"0 8px 20px rgba(0,0,0,.1)",marginTop:4}}>{gsRes.map(function(r,i){return <div key={i} onClick={function(){sGs("");if(r.t==="alumno")sVw("alumnos");if(r.t==="grupo"){sVw("grupos")}if(r.t==="lead")sVw("crm")}} style={{padding:"8px 12px",cursor:"pointer",borderBottom:"1px solid "+c.bdL,fontSize:12,fontFamily:F}} onMouseEnter={function(e){e.currentTarget.style.background=c.sfH}} onMouseLeave={function(e){e.currentTarget.style.background=""}}><div style={{color:c.tx,fontWeight:500}}>{r.l}</div><div style={{fontSize:10,color:c.txU}}>{r.s}</div></div>})}</div>}
</div></div>

{vw==="dashboard"&&<VDash/>}{vw==="alumnos"&&<VAlum/>}{vw==="profesores"&&<VProf/>}{vw==="grupos"&&<VGrup/>}{vw==="horarios"&&<VHor/>}{vw==="pagos"&&<VPag/>}{vw==="crm"&&<VCRM/>}
</main>

{/* Modals */}
<Mo open={md==="al"} onClose={cls} title={ed?"Editar alumno":"Inscribir alumno"}><AFrm item={ed} onSave={svAl} onClose={cls}/></Mo>
<Mo open={md==="gr"} onClose={cls} title={ed?"Editar grupo":"Crear grupo"} w={true}><GFrm item={ed} onSave={svGr} onDelete={dlGr} onClose={cls}/></Mo>
<Mo open={md==="ct"} onClose={cls} title={ed?"Editar contacto":"Nuevo lead"}><CFrm item={ed} onSave={svCt} onClose={cls}/></Mo>
<Mo open={et!==null} onClose={function(){sEt(null)}} title={"Tarifas — "+(doc.find(function(d){return d.id===et})||{}).nombre}>{et!==null&&<TFrm did={et}/>}</Mo>
<Mo open={addGrId!==null} onClose={cls} title="Agregar alumno al grupo">{addGrId!==null&&<div>{act.filter(function(a){return!a.grupo_id}).length===0?<p style={{color:c.txU,fontSize:13,fontFamily:F}}>No hay alumnos sin grupo disponibles</p>:act.filter(function(a){return!a.grupo_id}).map(function(a){return <div key={a.id} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid "+c.bdL,fontSize:13,fontFamily:F}}><span>{a.nombre} {a.apellido||""} — {a.nivel}</span><button style={Object.assign({},bP,{padding:"3px 10px",fontSize:11})} onClick={function(){uA(a.id,"grupo_id",addGrId);cls()}}>Agregar</button></div>})}</div>}</Mo>
{/* Confirm dialog */}
{cf&&<div style={{position:"fixed",inset:0,zIndex:2e3,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.4)"}}><div style={{background:c.sf,borderRadius:14,padding:28,width:"min(380px,90vw)",boxShadow:"0 20px 50px rgba(0,0,0,.2)",border:"1px solid "+c.bd,animation:"su .2s"}}><div style={{fontSize:15,color:c.tx,fontFamily:F,fontWeight:600,marginBottom:16}}>{cf.msg}</div><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><button style={bS} onClick={function(){sCf(null)}}>Cancelar</button><button style={Object.assign({},bP,{background:c.rd})} onClick={cf.ok}>Confirmar</button></div></div></div>}
</div></div>}
